name: Deploy Vercel to GitHub Pages

on:
  push:
    branches:
      - main  # 只有 main 分支的變更才會觸發部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Export static site from Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --output=out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out 
